"""Tests for eneru.config_doc (comment-preserving YAML editing)."""

import glob
import os
import stat
from pathlib import Path
from unittest.mock import patch

import pytest
from ruamel.yaml.comments import CommentedMap, CommentedSeq

from eneru import config_doc as cd
from eneru.config_doc import ConfigDocument, detect_indent, to_plain

pytestmark = pytest.mark.unit

REPO = Path(__file__).resolve().parent.parent
ALL_YAML = sorted(glob.glob(str(REPO / "examples" / "*.yaml"))
                  + glob.glob(str(REPO / "tests" / "e2e" / "*.yaml")))


def _doc(tmp_path, text, name="c.yaml"):
    p = tmp_path / name
    p.write_text(text)
    return ConfigDocument.load(p)


# ---------------------------------------------------------------------------
# Round trip
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("path", ALL_YAML, ids=lambda p: Path(p).name)
def test_round_trip_is_byte_identical(path):
    text = Path(path).read_text()
    assert ConfigDocument.load(path).dumps() == text


def test_round_trip_covers_repo_files():
    assert len(ALL_YAML) > 10


# ---------------------------------------------------------------------------
# detect_indent
# ---------------------------------------------------------------------------

def test_detect_indent_2_2():
    text = "a:\n  b: 1\nl:\n  - x\n  - y\n"
    assert detect_indent(text) == (2, 2)


def test_detect_indent_2_0_enterprise_style():
    text = "a:\n  b: 1\nl:\n- x\n- y\nm:\n  n:\n  - 1\n"
    assert detect_indent(text) == (2, 0)


def test_detect_indent_4_spaces():
    text = "a:\n    b: 1\n    c:\n        d: 2\nl:\n    - x\n"
    assert detect_indent(text) == (4, 4)


def test_detect_indent_defaults_and_comments():
    assert detect_indent("") == (2, 2)
    assert detect_indent("# only\n\nk: v\n") == (2, 2)


def test_detect_indent_parent_with_eol_comment():
    text = "a:  # note\n  b: 1\n"
    assert detect_indent(text) == (2, 2)


def test_four_space_file_round_trips(tmp_path):
    text = "a:\n    b: 1\nl:\n    - x\n    - y\n"
    assert _doc(tmp_path, text).dumps() == text


def test_enterprise_style_round_trips(tmp_path):
    text = "a:\n  b: 1\nl:\n- x\n- y\n"
    assert _doc(tmp_path, text).dumps() == text


# ---------------------------------------------------------------------------
# Load edge cases
# ---------------------------------------------------------------------------

def test_null_preserved(tmp_path):
    text = "logging:\n  file: null  # stdout only\n"
    d = _doc(tmp_path, text)
    assert d.dumps() == text
    assert d.get(("logging", "file")) is None


def test_load_missing_file_starts_empty_with_header(tmp_path):
    d = ConfigDocument.load(tmp_path / "nope.yaml")
    assert not d.existed
    assert d.data == {}
    assert "generated by `eneru config`" in d.dumps()


def test_load_empty_file(tmp_path):
    d = _doc(tmp_path, "")
    assert d.existed and d.data == {}


def test_load_comment_only_file(tmp_path):
    d = _doc(tmp_path, "# nothing here\n")
    assert isinstance(d.data, CommentedMap)
    assert len(d.data) == 0


def test_load_non_mapping_root_raises(tmp_path):
    with pytest.raises(ValueError, match="must be a YAML mapping"):
        _doc(tmp_path, "- a\n- b\n")


# ---------------------------------------------------------------------------
# get / has
# ---------------------------------------------------------------------------

def test_get_and_has(tmp_path):
    d = _doc(tmp_path, "a:\n  b: [1, 2]\n")
    assert d.get(("a", "b", 0)) == 1
    assert d.get(("a", "b", -1)) == 2
    assert d.get(("a", "b", 5), "dflt") == "dflt"
    assert d.get(("a", "b", -5), "dflt") == "dflt"
    assert d.get(("a", 0), "x") == "x"          # int into a mapping
    assert d.get(("a", "b", "k"), "y") == "y"   # str into a list
    assert d.get(("zz",)) is None
    assert d.has(("a", "b"))
    assert not d.has(("a", "c"))


# ---------------------------------------------------------------------------
# set
# ---------------------------------------------------------------------------

REF_LIKE = """\
ups:
  # The UPS name
  name: "UPS@host"
  check_interval: 1

# ======
# TRIGGERS
# ======
triggers:
  low_battery_threshold: 20
"""


def test_set_existing_key_keeps_comments(tmp_path):
    d = _doc(tmp_path, REF_LIKE)
    d.set(("ups", "name"), "other@host", comment="IGNORED")
    out = d.dumps()
    # ruamel keeps the original quoting style of the replaced scalar.
    assert '# The UPS name\n  name: "other@host"' in out
    assert "IGNORED" not in out
    assert d.modified


def test_set_same_value_is_noop(tmp_path):
    d = _doc(tmp_path, REF_LIKE)
    d.set(("ups", "check_interval"), 1)
    assert not d.modified
    assert d.dumps() == REF_LIKE


def test_set_new_key_writes_comment_and_lands_before_heading(tmp_path):
    d = _doc(tmp_path, REF_LIKE)
    d.set(("ups", "display_name"), "Lab", comment="Friendly name.")
    out = d.dumps()
    lines = out.splitlines()
    i = lines.index("  display_name: Lab")
    assert lines[i - 1] == "  # Friendly name."
    assert lines[i - 2] == "  check_interval: 1"
    # The section heading still directly precedes `triggers:`.
    t = lines.index("triggers:")
    assert lines[t - 1] == "# ======"
    assert lines[t - 2] == "# TRIGGERS"
    assert t > i
    import yaml
    assert yaml.safe_load(out)["ups"]["display_name"] == "Lab"


def test_set_new_key_eol_comment_stays_on_its_line(tmp_path):
    text = ("ups:\n  name: x\n  check_interval: 1  # poll fast\n\n"
            "# HEADING\ntriggers:\n  a: 1\n")
    d = _doc(tmp_path, text)
    d.set(("ups", "display_name"), "Lab")
    lines = d.dumps().splitlines()
    assert "  check_interval: 1  # poll fast" in lines
    i = lines.index("  display_name: Lab")
    t = lines.index("triggers:")
    assert lines[t - 1] == "# HEADING"
    assert i < t


def test_set_new_key_eol_comment_only_nothing_to_move(tmp_path):
    text = "ups:\n  name: x  # only eol\ntriggers:\n  a: 1\n"
    d = _doc(tmp_path, text)
    d.set(("ups", "display_name"), "Lab")
    out = d.dumps()
    assert "name: x  # only eol" in out
    assert out.index("display_name") < out.index("triggers:")


def test_set_new_key_with_nested_last_value(tmp_path):
    text = ("ups:\n  name: x\n  clgp:\n    enabled: true\n\n"
            "# HEADING\ntriggers:\n  a: 1\n")
    d = _doc(tmp_path, text)
    d.set(("ups", "display_name"), "Lab")
    lines = d.dumps().splitlines()
    i = lines.index("  display_name: Lab")
    t = lines.index("triggers:")
    assert lines[t - 1] == "# HEADING"
    assert i < t


def test_set_new_nested_section_value_takes_trailing(tmp_path):
    d = _doc(tmp_path, REF_LIKE)
    d.set(("ups", "clgp"), {"enabled": True, "duration": 60})
    lines = d.dumps().splitlines()
    t = lines.index("triggers:")
    assert lines[t - 1] == "# ======"
    assert lines.index("    duration: 60") < t


def test_set_new_section_gets_section_comment_via_lookup(tmp_path):
    d = _doc(tmp_path, REF_LIKE)
    helps = {("mqtt",): "MQTT section help", ("mqtt", "enabled"): "Enable it"}
    d.set(("mqtt", "enabled"), True, comment_lookup=helps.get)
    out = d.dumps()
    assert "\n\n# MQTT section help\nmqtt:\n  # Enable it\n  enabled: true" in out


def test_blank_line_before_new_top_level_section_only(tmp_path):
    d = _doc(tmp_path, "a: 1\n")
    d.set(("sec", "sub", "k"), 1, comment_lookup=lambda p: "h " + ".".join(p))
    out = d.dumps()
    assert "a: 1\n\n# h sec\nsec:\n  # h sec.sub\n  sub:\n    # h sec.sub.k\n    k: 1\n" == out


def test_comment_lookup_returning_none_skips_comment(tmp_path):
    d = _doc(tmp_path, "a: 1\n")
    d.set(("b", "c"), 2, comment_lookup=lambda p: None)
    assert d.dumps() == "a: 1\nb:\n  c: 2\n"


def test_new_section_created_takes_heading_from_previous_section(tmp_path):
    d = _doc(tmp_path, REF_LIKE)
    # `ups.nested.x` creates `nested` inside ups, whose last key carries the
    # TRIGGERS heading: it must move below the new subtree.
    d.set(("ups", "nested", "x"), 1)
    lines = d.dumps().splitlines()
    t = lines.index("triggers:")
    assert lines[t - 1] == "# ======"
    assert lines.index("    x: 1") < t


def test_set_creates_list_parent_and_index(tmp_path):
    d = _doc(tmp_path, "a: 1\n")
    d.set(("items", 0), "first")
    d.set(("items", 0), "changed")
    assert d.get(("items",)) == ["changed"]
    d.set(("items", 1), {"k": [1, 2]})
    assert isinstance(d.get(("items", 1)), CommentedMap)
    assert isinstance(d.get(("items", 1, "k")), CommentedSeq)


def test_set_replaces_scalar_parent_with_mapping(tmp_path):
    d = _doc(tmp_path, "a: 1\n")
    d.set(("a", "b"), 2)
    assert d.to_plain() == {"a": {"b": 2}}


def test_set_through_list_index_in_path(tmp_path):
    d = _doc(tmp_path, "servers:\n  - name: a\n")
    d.set(("servers", 0, "host"), "h", comment="Host.")
    assert "    # Host.\n    host: h" in d.dumps()


def test_comments_never_use_the_api_old_ruamel_ignores(tmp_path):
    # ruamel 0.16.6 silently drops yaml_set_comment_before_after_key for
    # appended keys, so comments are stored in the parser's own slots
    # instead. Make that API explode: comments must still be written.
    d = _doc(tmp_path, "a: 1\n")
    with patch.object(CommentedMap, "yaml_set_comment_before_after_key",
                      side_effect=AssertionError("must not be called")):
        d.set(("b",), 2, comment="x")
        d.set(("c", "d"), 3, comment_lookup=lambda p: "y")
    assert d.to_plain() == {"a": 1, "b": 2, "c": {"d": 3}}
    out = d.dumps()
    assert "# x\nb: 2" in out and "  # y\n  d: 3" in out


def test_comment_new_key_ignores_non_map_parent(tmp_path):
    d = _doc(tmp_path, "a: 1\n")
    d._comment_new_key(CommentedSeq(), "k", ("k",), lambda p: "x")  # no raise


def test_depth_column(tmp_path):
    d = _doc(tmp_path, "a:\n  b:\n    c: 1\nl:\n  - m: 1\n")
    assert d._depth_column(("a",)) == 0
    assert d._depth_column(("a", "b")) == 2
    assert d._depth_column(("a", "b", "c")) == 4
    assert d._depth_column(("l", 0, "m")) == 4


def test_flush_trailing_skips_empty_container(tmp_path):
    d = _doc(tmp_path, "a: 1\n")
    d._pending_trailing = [(CommentedMap(), object())]
    d._flush_trailing()
    assert d._pending_trailing == []


# ---------------------------------------------------------------------------
# append / delete
# ---------------------------------------------------------------------------

LIST_WITH_TRAILER = """\
servers:
  - name: a
    host: h1
  # Example (commented):
  # - name: z

# HEADING
local:
  x: 1
"""


def test_append_moves_trailing_comments_after_new_item(tmp_path):
    d = _doc(tmp_path, LIST_WITH_TRAILER)
    idx = d.append(("servers",), {"name": "b", "host": "h2"})
    assert idx == 1
    lines = d.dumps().splitlines()
    b = lines.index("  - name: b")
    t = lines.index("local:")
    assert lines[t - 1] == "# HEADING"
    assert b < t
    assert d.modified


def test_append_scalar_list_with_trailing(tmp_path):
    text = "urls:\n  - one\n\n# HEADING\nnext: 1\n"
    d = _doc(tmp_path, text)
    d.append(("urls",), "two")
    lines = d.dumps().splitlines()
    assert lines.index("  - two") < lines.index("# HEADING")


def test_append_creates_missing_list(tmp_path):
    d = _doc(tmp_path, "a: 1\n")
    assert d.append(("x", "y"), "v") == 0
    assert d.to_plain() == {"a": 1, "x": {"y": ["v"]}}


def test_append_without_trailing(tmp_path):
    d = _doc(tmp_path, "l:\n  - a\n")
    d.append(("l",), "b")
    assert d.dumps() == "l:\n  - a\n  - b\n"


def test_delete(tmp_path):
    d = _doc(tmp_path, "a:\n  b: 1\nl: [1, 2]\n")
    assert d.delete(("a", "b"))
    assert not d.delete(("a", "b"))
    assert d.delete(("l", 0))
    assert not d.delete(("l", 9))
    assert not d.delete(("a", 0))
    assert d.delete(("l",))
    assert not d.delete(("missing", "x"))
    assert d.to_plain() == {"a": {}}
    assert d.modified


# ---------------------------------------------------------------------------
# Trailing-comment helpers edge cases
# ---------------------------------------------------------------------------

def test_detach_trailing_on_empty_and_uncommented():
    assert cd._detach_trailing_comment(CommentedMap()) is None
    m = CommentedMap()
    m["a"] = 1
    assert cd._detach_trailing_comment(m) is None


def test_detach_trailing_whitespace_only_token(tmp_path):
    d = _doc(tmp_path, "a:\n  b: 1\n\nc: 2\n")
    # Only a blank line trails `b` -> nothing worth moving.
    assert cd._detach_trailing_comment(d.data["a"]) is None


def test_attach_trailing_noop_cases():
    cd._attach_trailing_comment(CommentedMap(), object())
    m = CommentedMap()
    m["a"] = 1
    cd._attach_trailing_comment(m, None)
    assert "a" not in m.ca.items


def test_attach_trailing_pads_short_entry():
    m = CommentedMap()
    m["a"] = 1
    m.ca.items["a"] = [None]
    tok = object()
    cd._attach_trailing_comment(m, tok)
    assert m.ca.items["a"][2] is tok and len(m.ca.items["a"]) == 4


# ---------------------------------------------------------------------------
# Group layout
# ---------------------------------------------------------------------------

LEGACY = """\
ups:
  name: "UPS@h"
docker:
  enabled: true
remote_servers:
  - name: nas
virtual_machines:
  enabled: false
filesystems:
  sync_enabled: true
triggers:
  low_battery_threshold: 20
"""


def test_layout_helpers_legacy(tmp_path):
    d = _doc(tmp_path, LEGACY)
    assert not d.is_multi_ups()
    assert d.ups_paths() == [("ups",)]
    assert d.group_base(0) == ()
    assert d.redundancy_paths() == []


def test_layout_helpers_multi(tmp_path):
    d = _doc(tmp_path, "ups:\n  - name: a\n  - name: b\n"
                       "redundancy_groups:\n  - name: r\n")
    assert d.is_multi_ups()
    assert d.ups_paths() == [("ups", 0), ("ups", 1)]
    assert d.group_base(1) == ("ups", 1)
    assert d.redundancy_paths() == [("redundancy_groups", 0)]


def test_layout_helpers_no_ups(tmp_path):
    d = _doc(tmp_path, "a: 1\n")
    assert d.ups_paths() == []


def test_convert_to_multi_ups_moves_sections_and_docker_alias(tmp_path):
    d = _doc(tmp_path, LEGACY)
    d.convert_to_multi_ups()
    plain = d.to_plain()
    assert plain["ups"] == [{
        "name": "UPS@h", "is_local": True,
        "remote_servers": [{"name": "nas"}],
        "virtual_machines": {"enabled": False},
        "containers": {"enabled": True, "runtime": "docker"},
        "filesystems": {"sync_enabled": True},
    }]
    assert "docker" not in plain and "triggers" in plain
    assert d.modified
    # Result is a valid multi-UPS config for the loader.
    from eneru.config import ConfigLoader
    cfg = ConfigLoader._parse_config(plain)
    assert cfg.ups_groups[0].is_local
    assert cfg.ups_groups[0].remote_servers[0].name == "nas"
    # Idempotent on the list form.
    before = d.dumps()
    d.convert_to_multi_ups()
    assert d.dumps() == before


def test_convert_to_multi_ups_keeps_containers_over_docker(tmp_path):
    d = _doc(tmp_path, "ups:\n  name: a\ncontainers:\n  enabled: true\n"
                       "docker:\n  enabled: false\n")
    d.convert_to_multi_ups()
    assert d.to_plain()["ups"][0]["containers"] == {"enabled": True}
    assert "docker" in d.to_plain()


def test_convert_to_multi_ups_plain_dict_and_missing(tmp_path):
    d = _doc(tmp_path, "a: 1\n")
    d.data["ups"] = {"name": "plain"}
    d.convert_to_multi_ups()
    assert d.to_plain()["ups"] == [{"name": "plain", "is_local": True}]
    d2 = _doc(tmp_path, "a: 1\n", name="d2.yaml")
    d2.convert_to_multi_ups()
    assert d2.to_plain()["ups"] == [{"is_local": True}]


# ---------------------------------------------------------------------------
# to_plain
# ---------------------------------------------------------------------------

def test_to_plain_types(tmp_path):
    d = _doc(tmp_path, "a:\n  i: 1\n  f: 1.5\n  b: true\n  n: null\n"
                       "  s: 'x'\n  l: [1, 'two']\n")
    plain = d.to_plain()
    assert plain == {"a": {"i": 1, "f": 1.5, "b": True, "n": None, "s": "x",
                           "l": [1, "two"]}}
    assert type(plain) is dict and type(plain["a"]) is dict
    assert type(plain["a"]["l"]) is list
    assert type(plain["a"]["i"]) is int and type(plain["a"]["f"]) is float
    assert type(plain["a"]["s"]) is str
    assert d.to_plain_at(("a", "l")) == [1, "two"]
    assert to_plain((1, 2)) == [1, 2]
    sentinel = object()
    assert to_plain(sentinel) is sentinel


def test_wrap_comment():
    text = " ".join(["word"] * 40)
    wrapped = cd._wrap_comment(text, width=20)
    assert all(len(line) <= 20 for line in wrapped.splitlines())
    assert cd._wrap_comment("a\nb") == "a\nb"


# ---------------------------------------------------------------------------
# save
# ---------------------------------------------------------------------------

def test_save_new_file_mode_0600(tmp_path):
    target = tmp_path / "sub" / "new.yaml"
    d = ConfigDocument.load(target)
    d.set(("ups", "name"), "a@b")
    assert d.save() == target
    assert stat.S_IMODE(target.stat().st_mode) == 0o600
    assert not (tmp_path / "sub" / "new.yaml.bak").exists()
    assert d.existed and not d.modified
    assert "name: a@b" in target.read_text()


def test_save_existing_keeps_mode_and_writes_bak(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    os.chmod(p, 0o640)
    d = ConfigDocument.load(p)
    d.set(("a",), 2)
    d.save()
    assert p.read_text() == "a: 2\n"
    assert stat.S_IMODE(p.stat().st_mode) == 0o640
    bak = tmp_path / "c.yaml.bak"
    assert bak.read_text() == "a: 1\n"
    assert stat.S_IMODE(bak.stat().st_mode) == 0o600


def test_save_without_backup_and_to_other_path(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    d = ConfigDocument.load(p)
    other = tmp_path / "other.yaml"
    other.write_text("old: 1\n")
    assert d.save(other, backup=False) == other
    assert other.read_text() == "a: 1\n"
    assert not (tmp_path / "other.yaml.bak").exists()
    assert d.path == other


def test_save_failure_cleans_tmp(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    d = ConfigDocument.load(p)
    d.set(("a",), 2)
    with patch.object(cd.os, "replace", side_effect=OSError("disk full")):
        with pytest.raises(OSError):
            d.save(backup=False)
    leftovers = [f for f in os.listdir(tmp_path) if f.startswith(".c.yaml.")]
    assert leftovers == []
    assert p.read_text() == "a: 1\n"


def test_save_failure_unlink_error_is_ignored(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    d = ConfigDocument.load(p)
    with patch.object(cd.os, "replace", side_effect=OSError("x")), \
            patch.object(cd.os, "unlink", side_effect=OSError("y")):
        with pytest.raises(OSError, match="x"):
            d.save(backup=False)


def test_snapshot_is_deep_copy(tmp_path):
    d = _doc(tmp_path, "a:\n  b: 1\n")
    snap = d.snapshot()
    d.set(("a", "b"), 2)
    assert snap["a"]["b"] == 1


def test_depth_column_scalar_in_path(tmp_path):
    d = _doc(tmp_path, "a: 1\n")
    assert d._depth_column(("a", "b")) == 0


# --- cross-version comment slots + old-ruamel emoji escapes -----------------

@pytest.mark.unit
def test_add_comment_before_first_key_initialises_missing_comment_list():
    m = CommentedMap()
    m["k"] = 1
    m.ca.comment = [None, None]
    cd._add_comment_before(m, "k", "first\n\nsecond", 2)
    values = [t.value for t in m.ca.comment[1]]
    assert values == ["# first\n", "\n", "# second\n"]


@pytest.mark.unit
def test_add_comment_before_after_empty_container_uses_parent_slot(tmp_path):
    doc = ConfigDocument.load(tmp_path / "x.yaml")
    doc.set(("a",), {})
    doc.set(("b",), 1, comment="about b")
    out = doc.dumps()
    assert "a: {}\n\n# about b\nb: 1\n" in out


@pytest.mark.unit
def test_add_comment_before_appends_to_token_without_final_newline():
    m = CommentedMap()
    m["a"] = 1
    m["b"] = 2
    m.ca.items["a"] = [None, None, cd._comment_token("  # eol", 0), None]
    cd._add_comment_before(m, "b", "about b", 0)
    assert m.ca.items["a"][2].value == "  # eol\n# about b\n"


@pytest.mark.unit
def test_unescape_astral_only_touches_double_quoted_scalars():
    text = ('title: "\\U0001F3E2  DC1"  # keep "\\U0001F3E2"\n'
            '  - "a\\U0001F600"\n'
            "plain: C:\\U0001F3E2\n"
            'bad: "\\U0000FFFE"\n')
    out = cd._unescape_astral(text)
    assert out.splitlines() == [
        'title: "\U0001F3E2  DC1"  # keep "\\U0001F3E2"',
        '  - "a\U0001F600"',
        "plain: C:\\U0001F3E2",
        'bad: "\\U0000FFFE"',  # non-printable stays escaped
    ]
    assert cd._unescape_astral("no escapes") == "no escapes"


@pytest.mark.unit
def test_dumps_restores_emoji_escaped_by_old_emitters(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text('notifications:\n  title: "\U0001F3E2 Lab"\n')
    doc = ConfigDocument.load(p)
    with patch.object(doc._yaml, "dump",
                      side_effect=lambda data, buf: buf.write(
                          'notifications:\n  title: "\\U0001F3E2 Lab"\n')):
        assert doc.dumps() == p.read_text()


@pytest.mark.unit
def test_dumps_empty_document_without_header_is_empty(tmp_path):
    doc = ConfigDocument.load(tmp_path / "x.yaml")
    doc.data = CommentedMap()
    assert doc.dumps() == ""


# --- code-review fixes: YAML 1.1 safety, delete/swap comments, durable save --

import errno as _errno  # noqa: E402

import yaml as _pyyaml  # noqa: E402
from ruamel.yaml.scalarstring import DoubleQuotedScalarString  # noqa: E402

REF = REPO / "examples" / "config-reference.yaml"


@pytest.mark.parametrize("value", ["12:30", "on", "yes", "0644", "1_000",
                                   "null", "a\nb", "key: [unclosed"])
def test_yaml11_safe_quotes_ambiguous_strings(value):
    out = cd.yaml11_safe(value)
    assert isinstance(out, DoubleQuotedScalarString)


@pytest.mark.parametrize("value", ["plain", "UPS@host", "/mnt/nas"])
def test_yaml11_safe_leaves_safe_strings(value):
    assert type(cd.yaml11_safe(value)) is str


def test_yaml11_safe_non_str_and_subclasses_untouched():
    assert cd.yaml11_safe(5) == 5
    assert cd.yaml11_safe(None) is None
    sub = DoubleQuotedScalarString("on")
    assert cd.yaml11_safe(sub) is sub


@pytest.mark.parametrize("value", ["12:30", "on", "yes", "0644", "1_000",
                                   "null", "plain"])
def test_set_round_trips_through_daemon_view(tmp_path, value):
    doc = _doc(tmp_path, "reports:\n  enabled: true\n")
    doc.set(("reports", "time"), value)
    doc.append(("reports", "include"), value)
    view = doc.daemon_view()
    assert view["reports"]["time"] == value
    assert view["reports"]["include"] == [value]
    assert _pyyaml.safe_load(doc.dumps())["reports"]["time"] == value


def test_daemon_view_non_mapping_is_empty(tmp_path):
    doc = _doc(tmp_path, "a: 1\n")
    with patch.object(doc, "dumps", return_value="- a\n"):
        assert doc.daemon_view() == {}


def _ref(tmp_path):
    p = tmp_path / "ref.yaml"
    p.write_text(REF.read_text())
    return ConfigDocument.load(p)


def test_delete_last_key_keeps_next_heading(tmp_path):
    doc = _ref(tmp_path)
    assert doc.delete(("triggers", "voltage_sensitivity"))
    out = doc.dumps()
    assert "voltage_sensitivity" not in _pyyaml.safe_load(out)["triggers"]
    assert "# BEHAVIOR\n# ====" in out
    i = out.index("# BEHAVIOR")
    assert out.index("behavior:", i) > i


def test_delete_last_list_item_keeps_next_heading(tmp_path):
    doc = _ref(tmp_path)
    assert doc.delete(("remote_servers", 0))
    out = doc.dumps()
    data = _pyyaml.safe_load(out)
    assert data["remote_servers"] == []
    assert "# Local Server Shutdown\nlocal_shutdown:" in out


def test_delete_first_of_several_keys_moves_comment_to_precomment(tmp_path):
    doc = _doc(tmp_path, "sec:\n  a: 1\n  # about b\n  b: 2\nz: 3\n")
    assert doc.delete(("sec", "a"))
    out = doc.dumps()
    assert _pyyaml.safe_load(out) == {"sec": {"b": 2}, "z": 3}
    assert "# about b" in out and out.index("# about b") < out.index("b: 2")


def test_delete_first_of_several_list_items(tmp_path):
    doc = _doc(tmp_path, "l:\n  - a\n  # about b\n  - b\n  - c\n")
    assert doc.delete(("l", 0))
    assert _pyyaml.safe_load(doc.dumps()) == {"l": ["b", "c"]}


def test_delete_first_key_with_existing_empty_precomment(tmp_path):
    doc = _doc(tmp_path, "sec:\n  a: 1\n  # about b\n  b: 2\n")
    doc.data["sec"].ca.comment = [None, None]
    doc.delete(("sec", "a"))
    assert "# about b" in doc.dumps()


def test_delete_middle_key_with_eol_comment(tmp_path):
    doc = _doc(tmp_path, "s:\n  a: 1\n  b: 2  # eol b\n  # about c\n  c: 3\n")
    assert doc.delete(("s", "b"))
    out = doc.dumps()
    assert "eol b" not in out
    assert "  a: 1\n  # about c\n  c: 3\n" in out


def test_delete_key_with_only_eol_comment(tmp_path):
    doc = _doc(tmp_path, "s:\n  a: 1\n  b: 2  # eol b\nz: 1\n")
    assert doc.delete(("s", "b"))
    assert _pyyaml.safe_load(doc.dumps()) == {"s": {"a": 1}, "z": 1}


def test_delete_key_whose_trailing_is_blank(tmp_path):
    doc = _doc(tmp_path, "s:\n  a: 1\n  b: 2\n\nz: 1\n")
    assert doc.delete(("s", "b"))
    assert _pyyaml.safe_load(doc.dumps()) == {"s": {"a": 1}, "z": 1}


def test_delete_empties_section_at_end_of_document(tmp_path):
    doc = _doc(tmp_path, "a: 1\nl:\n  - x: 1\n\n# trailing end comment\n")
    assert doc.delete(("l", 0))
    out = doc.dumps()
    assert _pyyaml.safe_load(out) == {"a": 1, "l": []}
    assert "trailing end comment" not in out


def test_delete_empties_nested_section_moves_to_ancestor_sibling(tmp_path):
    doc = _doc(tmp_path, "a:\n  l:\n    - x: 1\n\n# heading b\nb: 2\n")
    assert doc.delete(("a", "l", 0))
    out = doc.dumps()
    assert _pyyaml.safe_load(out) == {"a": {"l": []}, "b": 2}
    assert "# heading b\nb: 2" in out


def test_delete_shifts_sequence_comment_slots(tmp_path):
    doc = _doc(tmp_path, "l:\n  - a  # ca\n  - b  # cb\n  - c  # cc\n")
    doc.delete(("l", 0))
    out = doc.dumps()
    assert "- b  # cb" in out and "- c  # cc" in out and "# ca" not in out


def test_delete_missing_and_bad_index(tmp_path):
    doc = _doc(tmp_path, "l: [1]\ns: {a: 1}\n")
    assert not doc.delete(("l", 5))
    assert not doc.delete(("s", "zz"))
    assert not doc.delete(("nope", 0))


def test_reattach_after_deleted_nested_value(tmp_path):
    doc = _doc(tmp_path, "s:\n  a:\n    k: 1\n  b:\n    k: 2\n\n# head z\nz: 1\n")
    assert doc.delete(("s", "b"))
    out = doc.dumps()
    assert _pyyaml.safe_load(out) == {"s": {"a": {"k": 1}}, "z": 1}
    assert "# head z\nz: 1" in out


def test_reattach_merges_with_existing_eol(tmp_path):
    doc = _doc(tmp_path, "s:\n  a: 1  # eol a\n  b: 2\n\n# head z\nz: 1\n")
    doc.delete(("s", "b"))
    out = doc.dumps()
    assert "a: 1  # eol a" in out and "# head z\nz: 1" in out


def test_to_next_sibling_on_non_container_parent(tmp_path):
    doc = _doc(tmp_path, "a: 1\n")
    tok = cd._comment_token("\n# x\n", 0)
    doc._to_next_sibling_precomment(("a", "q"), tok)  # no crash, no-op
    assert doc.dumps() == "a: 1\n"


def test_swap_items_keeps_trailing_heading(tmp_path):
    doc = _doc(tmp_path, "l:\n  - a: 1\n  - b: 2\n\n# heading z\nz: 1\n")
    assert doc.swap_items(("l",), 0, 1)
    out = doc.dumps()
    assert _pyyaml.safe_load(out)["l"] == [{"b": 2}, {"a": 1}]
    assert "# heading z\nz: 1" in out
    assert doc.modified


def test_swap_items_without_trailing_and_bad_indices(tmp_path):
    doc = _doc(tmp_path, "l: [1, 2]\n")
    assert doc.swap_items(("l",), 1, 0)
    assert not doc.swap_items(("l",), 0, 2)
    assert not doc.swap_items(("l",), -1, 0)
    assert not doc.swap_items(("nope",), 0, 1)


def test_ensure_parent_rejects_scalar_list_item(tmp_path):
    doc = _doc(tmp_path, "remote_servers:\n  - oops\n")
    with pytest.raises(ValueError, match="not a mapping"):
        doc.set(("remote_servers", 0, "enabled"), True)


def test_ensure_parent_rejects_non_mapping_parent(tmp_path):
    doc = _doc(tmp_path, "l:\n  - [1, 2]\n")
    with pytest.raises(ValueError, match="not a mapping"):
        doc.set(("l", 0, "x", "y"), 1)


def test_convert_keeps_explicit_runtime(tmp_path):
    doc = _doc(tmp_path, "ups:\n  name: a\ndocker:\n  enabled: true\n  runtime: podman\n")
    doc.convert_to_multi_ups()
    assert doc.to_plain()["ups"][0]["containers"]["runtime"] == "podman"


def test_convert_non_dict_docker(tmp_path):
    doc = _doc(tmp_path, "ups:\n  name: a\ndocker: null\n")
    doc.convert_to_multi_ups()
    assert doc.to_plain()["ups"][0]["containers"] is None


def test_save_writes_through_symlink(tmp_path):
    real = tmp_path / "real.yaml"
    real.write_text("a: 1\n")
    link = tmp_path / "link.yaml"
    link.symlink_to(real)
    doc = ConfigDocument.load(link)
    doc.set(("a",), 2)
    saved = doc.save()
    assert saved == real.resolve()
    assert link.is_symlink()
    assert real.read_text() == "a: 2\n"


def test_backup_is_private_even_if_old_bak_was_public(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("secret: 1\n")
    os.chmod(p, 0o644)
    bak = tmp_path / "c.yaml.bak"
    bak.write_text("old\n")
    os.chmod(bak, 0o644)
    doc = ConfigDocument.load(p)
    doc.set(("secret",), 2)
    doc.save()
    assert stat.S_IMODE(bak.stat().st_mode) == 0o600
    assert bak.read_text() == "secret: 1\n"
    assert stat.S_IMODE(p.stat().st_mode) == 0o644


def test_backup_never_follows_a_planted_symlink(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    victim = tmp_path / "victim"
    victim.write_text("keep\n")
    (tmp_path / "c.yaml.bak").symlink_to(victim)
    doc = ConfigDocument.load(p)
    doc.set(("a",), 2)
    doc.save()
    # The link was replaced by a private regular file; its target untouched.
    bak = tmp_path / "c.yaml.bak"
    assert victim.read_text() == "keep\n"
    assert not bak.is_symlink() and bak.read_text() == "a: 1\n"
    assert stat.S_IMODE(bak.stat().st_mode) == 0o600
    assert p.read_text() == "a: 2\n"


def test_save_preserves_owner_as_root(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    doc = ConfigDocument.load(p)
    doc.set(("a",), 2)
    st = p.stat()
    with patch.object(cd.os, "geteuid", return_value=0), \
            patch.object(cd.os, "chown") as chown:
        doc.save()
    chown.assert_called_once()
    assert chown.call_args[0][1:] == (st.st_uid, st.st_gid)


def test_save_no_chown_when_not_root(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    doc = ConfigDocument.load(p)
    doc.set(("a",), 2)
    with patch.object(cd.os, "geteuid", return_value=1000), \
            patch.object(cd.os, "chown") as chown:
        doc.save()
    chown.assert_not_called()


@pytest.mark.parametrize("err", [_errno.EBUSY, _errno.EXDEV])
def test_save_bind_mount_falls_back_to_in_place(tmp_path, err):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    doc = ConfigDocument.load(p)
    doc.set(("a",), 2)
    with patch.object(cd.os, "replace", side_effect=OSError(err, "busy")):
        doc.save()
    assert p.read_text() == "a: 2\n"
    assert [x.name for x in tmp_path.iterdir() if x.name.startswith(".c.yaml.")] == []


def test_save_other_replace_error_reraises_and_cleans(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    doc = ConfigDocument.load(p)
    doc.set(("a",), 2)
    with patch.object(cd.os, "replace", side_effect=OSError(_errno.EACCES, "no")):
        with pytest.raises(OSError):
            doc.save()
    assert p.read_text() == "a: 1\n"
    assert [x.name for x in tmp_path.iterdir() if x.name.startswith(".c.yaml.")] == []


def test_fsync_dir_swallows_errors(tmp_path):
    with patch.object(cd.os, "open", side_effect=OSError("no")):
        cd._fsync_dir(tmp_path)
    with patch.object(cd.os, "fsync", side_effect=OSError("no")):
        cd._fsync_dir(tmp_path)


def test_crlf_file_round_trips_byte_identical(tmp_path):
    p = tmp_path / "c.yaml"
    raw = b"# head\r\nups:\r\n  name: a  # n\r\nb: 1\r\n"
    p.write_bytes(raw)
    doc = ConfigDocument.load(p)
    assert doc.newline == "\r\n"
    doc.modified = True
    doc.save()
    assert p.read_bytes() == raw
    doc.set(("b",), 2)
    doc.save()
    assert p.read_bytes() == raw.replace(b"b: 1", b"b: 2")


def test_utf8_emoji_preserved_regardless_of_locale(tmp_path, monkeypatch):
    p = tmp_path / "c.yaml"
    text = 'notifications:\n  title: "\u26a1 \U0001F3E2 Lab"\n'
    p.write_bytes(text.encode("utf-8"))
    monkeypatch.setenv("LC_ALL", "C")
    monkeypatch.setenv("LANG", "C")
    doc = ConfigDocument.load(p)
    doc.modified = True
    doc.save()
    assert p.read_bytes() == text.encode("utf-8")


def test_changed_on_disk(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    doc = ConfigDocument.load(p)
    assert not doc.changed_on_disk()
    p.write_text("a: 9\n")
    assert doc.changed_on_disk()
    doc.set(("a",), 2)
    doc.save()
    assert not doc.changed_on_disk()
    with patch("builtins.open", side_effect=OSError("gone")):
        assert not doc.changed_on_disk()
    new = ConfigDocument.load(tmp_path / "new.yaml")
    assert not new.changed_on_disk()


def test_reattach_concatenates_when_no_duplicate_newline(tmp_path):
    doc = _doc(tmp_path, "s:\n  a: 1\n  b: 2\n")
    parent = doc.data["s"]
    parent.ca.items["a"] = [None, None, cd._comment_token("  # x", 0), None]
    doc._reattach_comment(parent, 1, cd._comment_token("# y\n", 0), ("s",))
    assert parent.ca.items["a"][2].value == "  # x# y\n"


@pytest.mark.unit
def test_saved_view_tracks_the_file_on_disk(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    doc = ConfigDocument.load(p)
    assert doc.saved_view() == {"a": 1}
    doc.set(("a",), 2)
    assert doc.saved_view() == {"a": 1}
    doc.save()
    assert doc.saved_view() == {"a": 2}
    assert ConfigDocument.load(tmp_path / "new.yaml").saved_view() == {}
    doc._original_text = "- a list\n"
    assert doc.saved_view() == {}
    doc._original_text = "a: [unclosed\n"
    assert doc.saved_view() == {}


# --- container deployments: single-file bind mount in a read-only dir -------

def _eacces(*_a, **_k):
    raise PermissionError(13, "Permission denied")


@pytest.mark.unit
def test_save_rewrites_in_place_when_the_directory_is_not_writable(tmp_path):
    p = tmp_path / "config.yaml"
    p.write_text("a: 1\n")
    inode = p.stat().st_ino
    state = tmp_path / "state"
    state.mkdir()
    doc = ConfigDocument.load(p)
    doc.set(("a",), 2)
    real_open = os.open

    def bak_open(path, *a, **k):
        # The config's own directory refuses new files (like /etc/ups-monitor
        # in the image); the state directory accepts them.
        if Path(path).parent == tmp_path and ".bak" in str(path):
            raise PermissionError(13, "Permission denied")
        return real_open(path, *a, **k)
    with patch.object(cd.tempfile, "mkstemp", side_effect=_eacces), \
            patch.object(cd.os, "open", side_effect=bak_open):
        doc.save(backup_dir=state)
    assert p.read_text() == "a: 2\n" and p.stat().st_ino == inode
    assert doc.last_backup == state / "config.yaml.bak"
    assert (state / "config.yaml.bak").read_text() == "a: 1\n"
    assert stat.S_IMODE((state / "config.yaml.bak").stat().st_mode) == 0o600


@pytest.mark.unit
def test_save_mkstemp_errors_that_are_not_permissions_propagate(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    doc = ConfigDocument.load(p)
    with patch.object(cd.tempfile, "mkstemp", side_effect=OSError(28, "ENOSPC")):
        with pytest.raises(OSError):
            doc.save(backup=False)
    new = ConfigDocument.load(tmp_path / "new.yaml")
    new.set(("a",), 1)
    with patch.object(cd.tempfile, "mkstemp", side_effect=_eacces):
        with pytest.raises(PermissionError):
            new.save()  # nothing to rewrite in place


@pytest.mark.unit
def test_backup_fails_when_no_location_is_writable(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    with patch.object(cd.os, "open", side_effect=_eacces):
        with pytest.raises(PermissionError):
            ConfigDocument._write_backup(p, tmp_path)
    with patch.object(cd.os, "open", side_effect=OSError(28, "ENOSPC")):
        with pytest.raises(OSError):
            ConfigDocument._write_backup(p, tmp_path)


@pytest.mark.unit
def test_save_refuses_a_read_only_file_before_touching_anything(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    doc = ConfigDocument.load(p)
    doc.set(("a",), 2)
    with patch.object(cd.os, "access", return_value=False):
        with pytest.raises(PermissionError):
            doc.save(backup_dir=tmp_path)
    assert not (tmp_path / "c.yaml.bak").exists()
    assert p.read_text() == "a: 1\n"


@pytest.mark.unit
def test_writable_for_existing_and_new_files(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\n")
    assert ConfigDocument.load(p).writable()
    assert ConfigDocument.load(tmp_path / "x" / "y" / "new.yaml").writable()
    with patch.object(cd.os, "access", return_value=False):
        assert not ConfigDocument.load(p).writable()


@pytest.mark.unit
def test_unescape_is_escape_aware_and_covers_flow_forms():
    text = ('a: "\\\\U0001F3E2"\n'          # escaped backslash + text: untouched
            'b: ["\\U0001F3E2"]\n'          # flow sequence, no space
            'c: {k: "\\U0001F600", j: 1}\n'  # flow mapping
            'd: "x\\ny\\U0001F3E2"\n')      # other escapes kept, emoji restored
    out = cd._unescape_astral(text).splitlines()
    assert out[0] == 'a: "\\\\U0001F3E2"'
    assert out[1] == 'b: ["\U0001F3E2"]'
    assert out[2] == 'c: {k: "\U0001F600", j: 1}'
    assert out[3] == 'd: "x\\ny\U0001F3E2"'


@pytest.mark.unit
def test_convert_to_multi_keeps_root_section_headings(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text(
        "ups:\n  name: a\n"
        "remote_servers:\n  - name: nas\n\n"
        "# === LOCAL SHUTDOWN ===\n"
        "local_shutdown:\n  enabled: true\n")
    doc = ConfigDocument.load(p)
    doc.convert_to_multi_ups()
    out = doc.dumps()
    import yaml
    data = yaml.safe_load(out)
    assert data["ups"][0]["remote_servers"] == [{"name": "nas"}]
    # The heading still sits right above local_shutdown at the root.
    assert "# === LOCAL SHUTDOWN ===\nlocal_shutdown:" in out


@pytest.mark.unit
def test_swap_items_keeps_the_block_between_items(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("l:\n  - name: a\n\n  # about b\n  - name: b\n\n# heading\nz: 1\n")
    doc = ConfigDocument.load(p)
    assert doc.swap_items(("l",), 0, 1)
    out = doc.dumps()
    assert "# about b" in out and "# heading" in out
    import yaml
    assert yaml.safe_load(out)["l"] == [{"name": "b"}, {"name": "a"}]


@pytest.mark.unit
def test_delete_then_set_does_not_resurrect_old_comments(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("s:\n  a: 1\n  b: 2  # eol b\n  c: 3\n")
    doc = ConfigDocument.load(p)
    doc.delete(("s", "b"))
    assert "b" not in doc.data["s"].ca.items
    doc.set(("s", "b"), 5)
    out = doc.dumps()
    assert "# eol b" not in out and "b: 5" in out


@pytest.mark.unit
def test_backup_write_loops_over_short_writes(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("abcdef\n")
    real_write = os.write
    calls = []

    def one_byte(fd, data):
        calls.append(1)
        return real_write(fd, bytes(data[:1]))
    with patch.object(cd.os, "write", side_effect=one_byte):
        bak = ConfigDocument._write_backup(p)
    assert bak.read_text() == "abcdef\n" and len(calls) == 7
    with patch.object(cd.os, "write", return_value=0):
        with pytest.raises(OSError):
            ConfigDocument._write_backup(p)


@pytest.mark.unit
def test_in_place_write_shrinks_without_truncating_first(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("a: 1\nlong: " + "x" * 100 + "\n")
    cd._write_in_place(p, "a: 2\n")
    assert p.read_text() == "a: 2\n"


@pytest.mark.unit
def test_failed_backup_keeps_the_previous_good_backup(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("new\n")
    (tmp_path / "c.yaml.bak").write_text("old good backup\n")
    with patch.object(cd.os, "write", side_effect=OSError(28, "ENOSPC")):
        with pytest.raises(OSError):
            ConfigDocument._write_backup(p)
    assert (tmp_path / "c.yaml.bak").read_text() == "old good backup\n"
    assert not [f for f in os.listdir(tmp_path) if f.startswith(".c.yaml.bak")]


@pytest.mark.unit
def test_stale_backup_temp_file_is_replaced(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("x\n")
    (tmp_path / f".c.yaml.bak.{os.getpid()}").write_text("stale")
    assert ConfigDocument._write_backup(p).read_text() == "x\n"


@pytest.mark.unit
def test_relative_or_bogus_backup_dir_is_ignored(tmp_path):
    p = tmp_path / "c.yaml"
    p.write_text("x\n")
    assert ConfigDocument._write_backup(p, "relative/dir").parent == tmp_path
    assert ConfigDocument._write_backup(p, 123).parent == tmp_path
