"""Comment-preserving read/modify/write of an Eneru YAML config (ruamel.yaml).

ELI5: editing a config with PyYAML is like photocopying a hand-annotated recipe
through a machine that only copies the printed words -- every margin note (the
operator's comments) is gone from the copy. ruamel.yaml copies the whole page,
notes included, so `eneru config` can change one value in place and hand the
operator back THEIR file, not a stripped rewrite.

`ConfigDocument` wraps the round-trip tree with path-based get/set helpers the
TUI uses, keeps the file's own indentation style, writes atomically, keeps a
`.bak` of the previous version, and creates new files with mode 0600 (configs
carry NUT/SSH/Apprise secrets).
"""

import copy
import errno
import io
import os
import re
import tempfile
from collections import Counter
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple, Union

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq

PathKey = Union[str, int]
CommentLookup = Callable[[Tuple[PathKey, ...]], Optional[str]]
_MISSING = object()

NEW_FILE_HEADER = (
    "Eneru configuration - generated by `eneru config`.\n"
    "Every option is explained in examples/config-reference.yaml and\n"
    "https://eneru.readthedocs.io/latest/configuration/ ; run\n"
    "`eneru config check` after any hand edit."
)

# Legacy single-UPS configs keep these sections at the top level; the
# multi-UPS list form nests them under each `ups:` entry.
PER_GROUP_SECTIONS = ("remote_servers", "virtual_machines", "containers",
                      "filesystems")


# "This directory/file isn't writable for us" (read-only mount, wrong owner).
_NO_WRITE_ERRNOS = (errno.EACCES, errno.EPERM, errno.EROFS)


def _write_in_place(target: Path, text: str) -> None:
    """Rewrite ``target`` through its existing inode (bind-mount friendly)."""
    with open(target, "w", encoding="utf-8", newline="") as fh:
        fh.write(text)
        fh.flush()
        os.fsync(fh.fileno())


def _fsync_dir(path: Path) -> None:
    try:
        fd = os.open(str(path), os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(fd)
    except OSError:
        pass
    finally:
        os.close(fd)


def _represent_none(representer, _data):
    return representer.represent_scalar("tag:yaml.org,2002:null", "null")


def detect_indent(text: str) -> Tuple[int, int]:
    """Guess (mapping_indent, sequence_offset) from existing YAML text.

    ruamel.yaml applies ONE indentation style on dump, so re-emitting a file
    written in a different style would re-indent every line. We measure the
    dominant style (the most common key-under-key step, and how far a `- `
    dash sits from its parent key) and dump with that.
    """
    mapping_steps: Counter = Counter()
    offsets: Counter = Counter()
    prev: Optional[Tuple[int, str]] = None
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        if prev is not None:
            p_indent, p_text = prev
            parent_opens = p_text.endswith(":") or re.search(r":\s+#", p_text)
            if parent_opens and stripped.startswith("- ") and indent >= p_indent:
                offsets[indent - p_indent] += 1
            elif (parent_opens and indent > p_indent
                  and not p_text.startswith("- ")):
                mapping_steps[indent - p_indent] += 1
        prev = (indent, stripped)
    mapping = mapping_steps.most_common(1)[0][0] if mapping_steps else 2
    offset = offsets.most_common(1)[0][0] if offsets else 2
    return mapping, offset


def make_yaml(mapping: int = 2, offset: int = 2) -> YAML:
    y = YAML()
    y.preserve_quotes = True
    y.width = 4096
    y.indent(mapping=mapping, sequence=offset + 2, offset=offset)
    y.representer.add_representer(type(None), _represent_none)
    return y


def to_plain(node: Any) -> Any:
    """Deep-convert ruamel containers/scalars to plain Python types."""
    if isinstance(node, dict):
        return {str(k): to_plain(v) for k, v in node.items()}
    if isinstance(node, (list, tuple)):
        return [to_plain(v) for v in node]
    if isinstance(node, bool) or node is None:
        return node
    if isinstance(node, int):
        return int(node)
    if isinstance(node, float):
        return float(node)
    if isinstance(node, str):
        return str(node)
    return node


def yaml11_safe(value: Any) -> Any:
    """Quote a string the daemon's YAML 1.1 parser would read as non-string.

    ELI5: the editor (ruamel) and the daemon (PyYAML) speak two dialects of
    YAML. Written bare, `12:30` is a time string to one and the number 750 to
    the other; `on` is a word to one and True to the other. Any string that
    wouldn't come back from PyYAML as the same string gets double quotes, so
    both read exactly what the operator typed.
    """
    if not isinstance(value, str) or type(value) is not str:
        return value
    import yaml
    try:
        loaded = yaml.safe_load(value)
    except Exception:
        loaded = None
    if loaded == value and isinstance(loaded, str) and "\n" not in value:
        return value
    from ruamel.yaml.scalarstring import DoubleQuotedScalarString
    return DoubleQuotedScalarString(value)


def _plain_to_commented(value: Any) -> Any:
    if isinstance(value, str):
        return yaml11_safe(value)
    if isinstance(value, dict) and not isinstance(value, CommentedMap):
        m = CommentedMap()
        for k, v in value.items():
            m[k] = _plain_to_commented(v)
        return m
    if isinstance(value, (list, tuple)) and not isinstance(value, CommentedSeq):
        s = CommentedSeq()
        for v in value:
            s.append(_plain_to_commented(v))
        return s
    return value


def _wrap_comment(text: str, width: int = 78) -> str:
    """Soft-wrap a help paragraph into comment lines."""
    out: List[str] = []
    for para in text.split("\n"):
        words = para.split()
        line = ""
        for word in words:
            if line and len(line) + 1 + len(word) > width:
                out.append(line)
                line = word
            else:
                line = f"{line} {word}" if line else word
        out.append(line)
    return "\n".join(out)


def _last_comment_slot(node: Any) -> Tuple[Any, Any]:
    """(container, key) whose trailing comment follows ``node``'s last line."""
    while True:
        if isinstance(node, CommentedMap) and len(node):
            key = list(node.keys())[-1]
        elif isinstance(node, CommentedSeq) and len(node):
            key = len(node) - 1
        else:
            return None, None
        child = node[key]
        if isinstance(child, (CommentedMap, CommentedSeq)) and len(child):
            node = child
            continue
        return node, key


def _comment_pos(container: Any) -> int:
    # ruamel keeps a mapping key's trailing comment at slot 2, a sequence
    # item's at slot 0.
    return 2 if isinstance(container, CommentedMap) else 0


def _detach_trailing_comment(node: Any) -> Any:
    """Cut the comment block that trails ``node``'s last line.

    ELI5: ruamel files the next section's heading ("# === TRIGGERS ===") under
    the LAST key of the previous section, like a sticky note stuck to the
    bottom of the page. Appending a key after it would slide the new key below
    that sticky note, i.e. under the wrong heading. We peel the note off (an
    end-of-line comment on the key's own line stays put) so it can be re-stuck
    after the new key.
    """
    container, key = _last_comment_slot(node)
    if container is None:
        return None
    entry = container.ca.items.get(key)
    pos = _comment_pos(container)
    if not entry or len(entry) <= pos or entry[pos] is None:
        return None
    tok = entry[pos]
    value = tok.value or ""
    if value.startswith("#"):
        nl = value.find("\n")
        if nl < 0 or not value[nl + 1:].strip():
            return None
        head, rest = value[:nl + 1], value[nl + 1:]
        tok.value = head
        moved = copy.copy(tok)
        moved.value = "\n" + rest
        return moved
    if not value.strip():
        return None
    entry[pos] = None
    return tok


def _attach_trailing_comment(node: Any, tok: Any) -> None:
    container, key = _last_comment_slot(node)
    if container is None or tok is None:
        return
    entry = container.ca.items.setdefault(key, [None, None, None, None])
    while len(entry) < 4:
        entry.append(None)
    pos = _comment_pos(container)
    existing = entry[pos]
    if existing is None:
        entry[pos] = tok
        return
    # Merge, never replace: the slot may already hold the block that sits
    # between two list items (e.g. after swap_items reorders them).
    base = existing.value or ""
    extra = tok.value or ""
    if base.endswith("\n") and extra.startswith("\n"):
        extra = extra[1:]
    existing.value = base + extra


def _comment_token(text: str, column: int) -> Any:
    """A CommentToken built the same way on ruamel 0.16 .. 0.19."""
    from ruamel.yaml.error import CommentMark
    from ruamel.yaml.tokens import CommentToken
    return CommentToken(text, CommentMark(column), None)


def _comment_lines(text: str, column: int) -> str:
    pad = " " * column
    return "".join(f"{pad}# {line}\n" if line else "\n"
                   for line in text.split("\n"))


def _add_comment_before(parent: CommentedMap, key: Any, text: str,
                        column: int) -> None:
    """Put a comment block directly above ``parent[key]``.

    Stored exactly where ruamel's own parser stores such a comment, which
    every ruamel release emits (0.16.6 on RHEL 9 silently ignores
    ``yaml_set_comment_before_after_key`` for appended keys): above a
    mapping's FIRST key it's the mapping's own pre-comment; above any other
    key it's appended to the trailing comment of the previous sibling's last
    line.
    """
    keys = list(parent.keys())
    idx = keys.index(key)
    if idx == 0:
        # Mapping pre-comments: one token per line, no indentation in the
        # value (the emitter indents from the token's column).
        if parent.ca.comment is None:
            parent.ca.comment = [None, []]
        if parent.ca.comment[1] is None:
            parent.ca.comment[1] = []
        for line in text.split("\n"):
            parent.ca.comment[1].append(
                _comment_token(f"# {line}\n" if line else "\n", column))
        return
    # Trailing (post) comments carry their own indentation in the value.
    lines = _comment_lines(text, column)
    prev_value = parent[keys[idx - 1]]
    container, slot_key = _last_comment_slot(prev_value)
    if container is None:
        container, slot_key = parent, keys[idx - 1]
    entry = container.ca.items.setdefault(slot_key, [None, None, None, None])
    pos = _comment_pos(container)
    tok = entry[pos]
    if tok is None:
        entry[pos] = _comment_token("\n" + lines, column)
    else:
        value = tok.value or "\n"
        tok.value = (value if value.endswith("\n") else value + "\n") + lines


# A double-quoted scalar starts at a line's indent, after "- ", ": ", "? ",
# or a flow indicator; this keeps quote characters inside plain scalars
# (e.g. "it's") out of the scan.
_DQ_SCALAR = re.compile(r'(^[ \t]*(?:- )*|[:?-] |[,\[{] ?)"((?:[^"\\]|\\.)*)"')
# One escape at a time, so `\\U0001F3E2` (an escaped backslash, then the
# text "U0001F3E2") is never mistaken for a \U escape.
_DQ_ESCAPE = re.compile(r"\\(U[0-9A-Fa-f]{8}|.)", re.DOTALL)


def _unescape_astral(text: str) -> str:
    """Undo old ruamel's \\UXXXXXXXX escaping of emoji in double quotes.

    ruamel < 0.18 escapes every character above U+FFFD inside double-quoted
    scalars even with allow_unicode, so a title like "🏢 DC1" would be
    rewritten as "\\U0001F3E2 DC1" on RHEL 9 / Debian 12. Inside double
    quotes both spellings are the SAME string, so restoring the literal
    character keeps the operator's file byte-identical.
    """
    if "\\U" not in text:
        return text

    def fix_scalar(m: "re.Match[str]") -> str:
        def repl(e: "re.Match[str]") -> str:
            body = e.group(1)
            if len(body) == 9:  # U + 8 hex digits
                ch = chr(int(body[1:], 16))
                if ch.isprintable():
                    return ch
            return e.group(0)
        return f'{m.group(1)}"{_DQ_ESCAPE.sub(repl, m.group(2))}"'

    return "\n".join(_DQ_SCALAR.sub(fix_scalar, line)
                     for line in text.split("\n"))


class ConfigDocument:
    """A YAML config file loaded for comment-preserving editing."""

    def __init__(self, path: Union[str, Path], data: CommentedMap, *,
                 existed: bool, mapping: int = 2, offset: int = 2,
                 original_text: str = ""):
        self.path = Path(path)
        self.data = data
        self.existed = existed
        self.modified = False
        self._mapping = mapping
        self._offset = offset
        self._yaml = make_yaml(mapping, offset)
        self._original_text = original_text
        self._pending_trailing: List[Tuple[Any, Any]] = []
        self.newline = "\n"
        self.last_backup: Optional[Path] = None

    # -- construction ---------------------------------------------------

    @classmethod
    def load(cls, path: Union[str, Path]) -> "ConfigDocument":
        """Load ``path`` (or start an empty document if it doesn't exist).

        Raises ValueError when the file exists but isn't a YAML mapping.
        """
        p = Path(path)
        if not p.exists():
            data = CommentedMap()
            data.yaml_set_start_comment(NEW_FILE_HEADER)
            return cls(p, data, existed=False)
        with open(p, "r", encoding="utf-8", newline="") as fh:
            raw = fh.read()
        newline = "\r\n" if "\r\n" in raw else "\n"
        text = raw.replace("\r\n", "\n")
        mapping, offset = detect_indent(text)
        y = make_yaml(mapping, offset)
        data = y.load(text) if text.strip() else CommentedMap()
        if data is None:
            data = CommentedMap()
        if not isinstance(data, CommentedMap):
            raise ValueError(f"{p}: the config root must be a YAML mapping")
        doc = cls(p, data, existed=True, mapping=mapping, offset=offset,
                  original_text=raw)
        doc.newline = newline
        return doc

    # -- path helpers ---------------------------------------------------

    def get(self, path: Sequence[PathKey], default: Any = None) -> Any:
        node: Any = self.data
        for key in path:
            if isinstance(key, int):
                if not isinstance(node, list) or key >= len(node) or key < -len(node):
                    return default
                node = node[key]
            else:
                if not isinstance(node, dict) or key not in node:
                    return default
                node = node[key]
        return node

    def has(self, path: Sequence[PathKey]) -> bool:
        return self.get(path, _MISSING) is not _MISSING

    def _ensure_parent(self, path: Sequence[PathKey],
                       comment_lookup: Optional[CommentLookup] = None) -> Any:
        node: Any = self.data
        for i, key in enumerate(path[:-1]):
            nxt = path[i + 1]
            if isinstance(key, int):
                node = node[key]
                if not isinstance(node, (dict, list)):
                    raise ValueError(
                        f"{'.'.join(str(k) for k in path[:i + 1])} is "
                        f"{node!r}, not a mapping; fix it by hand first")
                continue
            if not isinstance(node, dict):
                raise ValueError(
                    f"{'.'.join(str(k) for k in path[:i])} is not a mapping")
            if key not in node or not isinstance(node[key], (dict, list)):
                created = key not in node
                trailing = (_detach_trailing_comment(node)
                            if created and isinstance(node, CommentedMap) else None)
                node[key] = CommentedSeq() if isinstance(nxt, int) else CommentedMap()
                if trailing is not None:
                    self._pending_trailing.append((node[key], trailing))
                if created:
                    self._comment_new_key(node, key, tuple(path[:i + 1]),
                                          comment_lookup)
            node = node[key]
        return node

    def _comment_new_key(self, parent: Any, key: str, path: Tuple[PathKey, ...],
                         comment_lookup: Optional[CommentLookup]) -> None:
        if comment_lookup is None or not isinstance(parent, CommentedMap):
            return
        text = comment_lookup(path)
        if not text:
            return
        # A blank line before each new top-level section keeps files readable.
        before = ("\n" if len(path) == 1 else "") + _wrap_comment(text)
        _add_comment_before(parent, key, before, self._depth_column(path))

    def _flush_trailing(self) -> None:
        """Re-attach section-heading comments peeled off during creation."""
        for container, tok in self._pending_trailing:
            if isinstance(container, (CommentedMap, CommentedSeq)) and len(container):
                _attach_trailing_comment(container, tok)
        self._pending_trailing = []

    def set(self, path: Sequence[PathKey], value: Any, *,
            comment: Optional[str] = None,
            comment_lookup: Optional[CommentLookup] = None) -> None:
        """Set ``path`` to ``value``.

        When the key is NEW, ``comment`` (or ``comment_lookup(path)``) is
        written above it; sections created on the way get their own comment
        from ``comment_lookup``. Existing keys keep their existing comments.
        """
        if comment is None and comment_lookup is not None:
            comment = comment_lookup(tuple(path))
        parent = self._ensure_parent(path, comment_lookup)
        key = path[-1]
        value = _plain_to_commented(value)
        if isinstance(key, int):
            if key == len(parent):
                parent.append(value)
            else:
                parent[key] = value
        else:
            is_new = key not in parent
            if not is_new and parent[key] == value and type(parent[key]) is type(value):
                return
            trailing = (_detach_trailing_comment(parent)
                        if is_new and isinstance(parent, CommentedMap) else None)
            parent[key] = value
            if trailing is not None:
                if isinstance(value, (CommentedMap, CommentedSeq)) and len(value):
                    _attach_trailing_comment(value, trailing)
                else:
                    entry = parent.ca.items.setdefault(key, [None, None, None, None])
                    entry[2] = trailing
            if is_new and comment and isinstance(parent, CommentedMap):
                before = ("\n" if len(path) == 1 else "") + _wrap_comment(comment)
                _add_comment_before(parent, key, before, self._depth_column(path))
        self._flush_trailing()
        self.modified = True

    def _depth_column(self, path: Sequence[PathKey]) -> int:
        """Indentation column of the last key in ``path``.

        Root keys sit at column 0; a nested mapping adds the mapping indent;
        a list moves content to ``offset + 2`` (after the "- " dash); a list
        item's own mapping keys share that content column.
        """
        col = 0
        node: Any = self.data
        for key in path[:-1]:
            child = node[key]
            if not isinstance(key, int):
                if isinstance(child, list):
                    col += self._offset + 2
                elif isinstance(child, dict):
                    col += self._mapping
            node = child
        return col

    def delete(self, path: Sequence[PathKey]) -> bool:
        """Remove ``path``; the comment block after it survives.

        ruamel files the NEXT key's (or section's) comment under the element
        being deleted; it is moved to the previous sibling so "reset to
        default" never eats a neighbour's heading.
        """
        parent = self.get(path[:-1], None) if len(path) > 1 else self.data
        key = path[-1]
        if isinstance(key, int):
            if not (isinstance(parent, list) and 0 <= key < len(parent)):
                return False
        elif not (isinstance(parent, dict) and key in parent):
            return False
        tok = self._detach_element_comment(parent, key)
        keys = list(range(len(parent))) if isinstance(parent, list) else list(parent)
        idx = keys.index(key)
        # CommentedSeq.__delitem__ already re-keys the later items' comment
        # slots (ruamel 0.16+); shifting them again would misplace them.
        del parent[key]
        if isinstance(parent, CommentedMap):
            # CommentedMap keeps the deleted key's comment slot; a later set()
            # of the same key would resurrect the old EOL comment/heading.
            parent.ca.items.pop(key, None)
        if tok is not None:
            self._reattach_comment(parent, idx, tok, path[:-1])
        self.modified = True
        return True

    @staticmethod
    def _detach_element_comment(parent: Any, key: Any) -> Any:
        """Cut the comment trailing ``parent[key]`` (EOL comment excluded)."""
        value = parent[key]
        if isinstance(value, (CommentedMap, CommentedSeq)) and len(value):
            return _detach_trailing_comment(value)
        entry = parent.ca.items.get(key)
        pos = _comment_pos(parent)
        if not entry or len(entry) <= pos or entry[pos] is None:
            return None
        tok = entry[pos]
        text = tok.value or ""
        if text.startswith("#"):
            nl = text.find("\n")
            if nl < 0 or not text[nl + 1:].strip():
                return None
            moved = copy.copy(tok)
            moved.value = "\n" + text[nl + 1:]
            return moved
        return tok if text.strip() else None

    def _reattach_comment(self, parent: Any, idx: int, tok: Any,
                          parent_path: Sequence[PathKey]) -> None:
        keys = list(range(len(parent))) if isinstance(parent, list) else list(parent)
        if idx > 0:
            prev = keys[idx - 1]
            container, slot = _last_comment_slot(parent[prev])
            if container is None:
                container, slot = parent, prev
        elif not keys:
            # The section became empty (`key: []` / `{}`). ruamel can't hang a
            # comment on an empty flow collection; its own parser stores such
            # a block as the NEXT key's pre-comment, so do the same, walking
            # up until some ancestor has a following sibling.
            self._to_next_sibling_precomment(tuple(parent_path), tok)
            return
        else:
            # Deleted the FIRST element: the block now precedes the new first
            # element, i.e. it becomes the container's pre-comment.
            if isinstance(parent, CommentedMap):
                if parent.ca.comment is None:
                    parent.ca.comment = [None, []]
                if parent.ca.comment[1] is None:
                    parent.ca.comment[1] = []
                for line in (tok.value or "").split("\n")[1:]:
                    if not line.strip():
                        continue
                    col = len(line) - len(line.lstrip(" "))
                    parent.ca.comment[1].append(
                        _comment_token(line.strip() + "\n", col))
            return
        entry = container.ca.items.setdefault(slot, [None, None, None, None])
        pos = _comment_pos(container)
        if entry[pos] is None:
            entry[pos] = tok
        else:
            base = entry[pos].value or ""
            extra = tok.value or ""
            if base.endswith("\n") and extra.startswith("\n"):
                extra = extra[1:]
            entry[pos].value = base + extra

    def _to_next_sibling_precomment(self, path: Tuple[PathKey, ...],
                                    tok: Any) -> None:
        while path:
            container = self.get(path[:-1], None) if len(path) > 1 else self.data
            key = path[-1]
            keys = (list(range(len(container))) if isinstance(container, list)
                    else list(container) if isinstance(container, dict) else [])
            if key in keys and keys.index(key) + 1 < len(keys):
                nxt = keys[keys.index(key) + 1]
                tokens = []
                for line in (tok.value or "").split("\n")[1:-1]:
                    if line.strip():
                        tokens.append(_comment_token(
                            line.strip() + "\n", len(line) - len(line.lstrip(" "))))
                    else:
                        tokens.append(_comment_token("\n", 0))
                entry = container.ca.items.setdefault(nxt, [None, None, None, None])
                entry[1] = tokens + list(entry[1] or [])
                return
            path = path[:-1]
        # Nothing follows anywhere: the block trailed the end of the file.

    def swap_items(self, path: Sequence[PathKey], i: int, j: int) -> bool:
        """Swap two list items; the trailing section comment stays last."""
        seq = self.get(path, None)
        if not isinstance(seq, list) or not (0 <= i < len(seq) and 0 <= j < len(seq)):
            return False
        trailing = _detach_trailing_comment(seq)
        seq[i], seq[j] = seq[j], seq[i]
        if trailing is not None:
            _attach_trailing_comment(seq, trailing)
        self.modified = True
        return True

    def append(self, path: Sequence[PathKey], value: Any) -> int:
        seq = self.get(path, None)
        if not isinstance(seq, list):
            self.set(path, [])
            seq = self.get(path)
        trailing = _detach_trailing_comment(seq)
        item = _plain_to_commented(value)
        seq.append(item)
        if trailing is not None:
            _attach_trailing_comment(seq, trailing)
        self.modified = True
        return len(seq) - 1

    # -- group layout -----------------------------------------------------

    def is_multi_ups(self) -> bool:
        return isinstance(self.data.get("ups"), list)

    def ups_paths(self) -> List[Tuple[PathKey, ...]]:
        ups = self.data.get("ups")
        if isinstance(ups, list):
            return [("ups", i) for i in range(len(ups))]
        if isinstance(ups, dict):
            return [("ups",)]
        return []

    def group_base(self, ups_index: int) -> Tuple[PathKey, ...]:
        """Where a UPS group's resources (remote_servers, ...) live."""
        return ("ups", ups_index) if self.is_multi_ups() else ()

    def redundancy_paths(self) -> List[Tuple[PathKey, ...]]:
        groups = self.data.get("redundancy_groups")
        if isinstance(groups, list):
            return [("redundancy_groups", i) for i in range(len(groups))]
        return []

    def convert_to_multi_ups(self) -> None:
        """Turn a legacy single-UPS config into the multi-UPS list form.

        The legacy shape is always the local UPS, so the entry gets
        ``is_local: true`` and takes the top-level per-group sections with it
        (`docker:` becomes `containers:`). Global sections (triggers, ...)
        stay at the top level where multi-UPS entries inherit them.
        """
        ups = self.data.get("ups")
        if isinstance(ups, list):
            return
        entry = ups if isinstance(ups, CommentedMap) else CommentedMap()
        if isinstance(ups, dict) and not isinstance(ups, CommentedMap):
            for k, v in ups.items():
                entry[k] = v
        entry["is_local"] = True
        if "containers" not in self.data and "docker" in self.data:
            docker = self.data.pop("docker")
            # The legacy `docker:` alias forced the Docker runtime; `auto`
            # would prefer Podman and stop the wrong containers.
            if isinstance(docker, dict):
                docker.setdefault("runtime", "docker")
            self.data["containers"] = docker
        for section in PER_GROUP_SECTIONS:
            if section in self.data:
                # The block trailing a moved section (usually the NEXT
                # section's heading) belongs to the root: keep it there,
                # exactly like delete() does.
                tok = self._detach_element_comment(self.data, section)
                idx = list(self.data).index(section)
                entry[section] = self.data.pop(section)
                if tok is not None:
                    self._reattach_comment(self.data, idx, tok, ())
        seq = CommentedSeq()
        seq.append(entry)
        self.data["ups"] = seq
        self.modified = True

    # -- output ---------------------------------------------------------

    def to_plain(self) -> Dict[str, Any]:
        return to_plain(self.data)

    def to_plain_at(self, path: Sequence[PathKey]) -> Any:
        return to_plain(self.get(path))

    def daemon_view(self) -> Dict[str, Any]:
        """The document exactly as the daemon will read it (PyYAML, YAML 1.1).

        ruamel reads YAML 1.2, where `yes`, `on` and `0644` differ from the
        daemon's YAML 1.1. Every check and every displayed value uses this
        view so the editor never disagrees with the daemon.
        """
        import yaml
        data = yaml.safe_load(self.dumps())
        return data if isinstance(data, dict) else {}

    def dumps(self) -> str:
        if not self.data:
            # ruamel 0.17 crashes dumping a comment-only empty mapping; an
            # all-comment file loads as {} anyway.
            start = self.data.ca.comment[1] if self.data.ca.comment else None
            return "".join(t.value for t in (start or []))
        buf = io.StringIO()
        self._yaml.dump(self.data, buf)
        return _unescape_astral(buf.getvalue())

    def _serialized(self) -> str:
        text = self.dumps()
        return text.replace("\n", self.newline) if self.newline != "\n" else text

    def saved_view(self) -> Dict[str, Any]:
        """The last saved (or loaded) file as the daemon reads it; {} if new."""
        import yaml
        try:
            data = yaml.safe_load(self._original_text) if self._original_text else None
        except Exception:
            return {}
        return data if isinstance(data, dict) else {}

    def changed_on_disk(self) -> bool:
        """True when someone else rewrote the file since we loaded/saved it."""
        if not self.existed or not self.path.exists():
            return False
        try:
            with open(self.path, "r", encoding="utf-8", newline="") as fh:
                return fh.read() != self._original_text
        except OSError:
            return False

    def writable(self) -> bool:
        """Can this process rewrite the config file (or create it)?"""
        target = Path(os.path.realpath(self.path))
        if target.exists():
            return os.access(target, os.W_OK)
        parent = target.parent
        while not parent.exists() and parent != parent.parent:
            parent = parent.parent
        return os.access(parent, os.W_OK)

    def save(self, path: Optional[Union[str, Path]] = None, *,
             backup: bool = True,
             backup_dir: Optional[Union[str, Path]] = None) -> Path:
        """Durably write the document; keep a private `.bak` of the old file.

        ELI5: normally we write a fresh copy next to the file and swap it in
        (a power cut mid-write can't leave half a config). In a container the
        config is often a single-file bind mount inside a directory we may not
        write to: then the copy can't be made next to it, so the file itself
        is rewritten in place (same inode, so the host sees the change), and
        the `.bak` goes to ``backup_dir`` (the persistent state volume).

        A symlinked config is written through to its real file; mode and
        owner of an existing file are kept. ``self.last_backup`` records
        where the previous version went.
        """
        target = Path(os.path.realpath(path if path else self.path))
        text = self._serialized()
        target.parent.mkdir(parents=True, exist_ok=True)
        mode, owner = 0o600, None
        self.last_backup = None
        if target.exists() and not os.access(target, os.W_OK):
            # Refuse before touching anything (no stray .bak for a :ro mount).
            raise PermissionError(errno.EACCES, "config file is read-only for "
                                  "this user", str(target))
        if target.exists():
            st = target.stat()
            mode, owner = st.st_mode & 0o777, (st.st_uid, st.st_gid)
            if backup:
                self.last_backup = self._write_backup(target, backup_dir)
        try:
            fd, tmp = tempfile.mkstemp(prefix=f".{target.name}.",
                                       dir=str(target.parent))
        except OSError as exc:
            if exc.errno not in _NO_WRITE_ERRNOS or not target.exists():
                raise
            _write_in_place(target, text)
            return self._saved(target, text)
        try:
            with os.fdopen(fd, "w", encoding="utf-8", newline="") as fh:
                fh.write(text)
                fh.flush()
                os.fsync(fh.fileno())
            os.chmod(tmp, mode)
            if owner is not None and hasattr(os, "geteuid") and os.geteuid() == 0:
                os.chown(tmp, *owner)
            try:
                os.replace(tmp, target)
            except OSError as exc:
                if exc.errno not in (errno.EBUSY, errno.EXDEV):
                    raise
                os.unlink(tmp)
                _write_in_place(target, text)
            _fsync_dir(target.parent)
        except BaseException:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise
        return self._saved(target, text)

    def _saved(self, target: Path, text: str) -> Path:
        self.path = target
        self.existed = True
        self.modified = False
        self._original_text = text
        return target

    @staticmethod
    def _write_backup(target: Path,
                      backup_dir: Optional[Union[str, Path]] = None) -> Path:
        """Copy the current file to `<name>.bak`; return where it went.

        Created 0600 from the first byte (it holds the same secrets as the
        config); O_NOFOLLOW refuses a planted symlink. When the config's own
        directory isn't writable, the copy goes to ``backup_dir``.
        """
        candidates = [target.with_name(target.name + ".bak")]
        if backup_dir:
            candidates.append(Path(backup_dir) / (target.name + ".bak"))
        flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC | getattr(os, "O_NOFOLLOW", 0)
        for i, bak in enumerate(candidates):
            try:
                fd = os.open(str(bak), flags, 0o600)
            except OSError as exc:
                if exc.errno in _NO_WRITE_ERRNOS and i + 1 < len(candidates):
                    continue
                raise
            try:
                os.fchmod(fd, 0o600)
                with open(target, "rb") as src:
                    os.write(fd, src.read())
                os.fsync(fd)
            finally:
                os.close(fd)
            return bak
        raise AssertionError("unreachable")  # pragma: no cover

    def snapshot(self) -> CommentedMap:
        """Deep copy for undo/cancel of a sub-editor."""
        return copy.deepcopy(self.data)
